@startuml
'https://plantuml.com/class-diagram

skinparam defaultFontName Droid Sans
skinparam linetype ortho
skinparam nodesep 60
set separator none
skinparam class {
  BackgroundColor White
  BackgroundColor<<Settings>> Wheat
}

package "Espécies da Amazônia" <<Frame>> {
  class Post {
    - id: String {PK}
    ---
    - title: String(100) NOT NULL
    - image_url: String NOT NULL
    - date_picture: LocalDate
    - popular_name: String(100)
    - description: String
    - verified: Boolean NOT NULL
    - published_at: LocalDateTime NOT NULL
    - updated_at: LocalDateTime NOT NULL
    - specie: Int {FK}
    - locality: Int {FK}
  }

  class Locality {
    - id: Int {PK}
    ---
    - name: String(100)
    - city: Int {FK}
  }

  class family {
    - id: Int {PK}
    ---
    - name: String(100)
  }

  class gender {
    - id: Int {PK}
    ---
    - name: String(100)
    - family: Int {FK}
  }

  class Specie {
    - id: Int {PK}
    ---
    - name: String(100)
    - gender: Int {FK}
  }

  class User {}

  Post }o-- Specie : Contains
  Post }o-- User
  gender }o-- family : Belongs To
  Specie }o-- gender : Is Of
}

database {
    class State <<Settings>> {
      - id: Int {PK}
      ---
      - name: String(100)
      - abbreviation: String(2)
    }

    class City <<Settings>> {
      - id: Int {PK}
      ---
      - name: String(100)
      - state: Int {FK}
    }

  Post }o-l- Locality : Located In
  City }o-- State : Belongs To
  Locality }o-- City : Is In
}

@enduml
